# Generated by Django 3.2.9 on 2021-11-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20211128_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='source',
            field=models.ManyToManyField(to='newsapp.Source'),
        ),
    ]
